name: "Michael-F-Bryan"
description: "Keep an eye on how long your GitHub Actions jobs are taking."
author: "Michael-F-Bryan <michaelfbryan@gmail.com>"
inputs:
  token:
    required: true
    description: "A GitHub token that can access this repo (e.g. `${{ secrets.GITHUB_TOKEN }}`)"
runs:
  using: "node16"
  main: "dist/index.js"
